# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d3ca58e5f9620556ff71eb341a3758558ab3831df710aa20162346b95b877a0e1c21e2ddd38320cca42fe0595ec3d5df98c65cbdae80036c25788d61cf6254a2

test:
  secret_key_base: 13611be5489e2ea34cd4b3c8ccf6a0596933b28db64ab80184fe865edde80297ac263f53af10125f6220e89fc7cd685adabf66283339146b76ad57cec58795f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
